version: '3'
services:
    counts_db:
      image: mdillon/postgis:10
      container_name: counts_db
      ports:
        - "${POSTGRES_PORT}:5432"
      volumes:
        - ./pg_data:/data
      env_file: ./.env
      environment:
        - PGDATA=/data
